/* BioGlyph project page widgets.
 *
 * Structure copied from scvision/interactive.js: one file, no dependencies, no build step, and
 * one self-guarding IIFE per widget so a missing element or a failed fetch takes out that widget
 * alone. Charts are hand-written inline SVG strings.
 *
 * Every number rendered here comes from assets/regions.json or assets/results.json, both
 * generated by build_data.py out of the manuscript's own figure data. Nothing is typed into the
 * markup, so the page cannot drift from the paper.
 */
(function () {
  "use strict";

  var INK = "#17202c", SOFT = "#465262", MUTED = "#707a86", LINE = "#d9d6ce",
      ACCENT = "#a83f35", BLUE = "#476d89", WARM = "#f5f3ee";

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }
  function num(n) { return Number(n).toLocaleString(); }
  function svg(inner, vw, vh) {
    return '<svg viewBox="0 0 ' + vw + " " + vh + '" preserveAspectRatio="xMidYMid meet" ' +
           'role="img" xmlns="http://www.w3.org/2000/svg">' + inner + "</svg>";
  }

  /* ------------------------------------------------------------------ chart
   * Accuracy by representation. One series, sorted, direct labels, plus the two things the
   * markup version could not show: the confidence interval as a whisker, and the blind floor as
   * a reference line. Whether 70.6 and 64.3 overlap is exactly what a reader wants to see.
   */
  (function () {
    var host = document.getElementById("accChart");
    if (!host) return;

    fetch("assets/results.json").then(function (r) { return r.json(); }).then(function (d) {
      var W = 1000, rowH = 46, padT = 34, padB = 30,
          H = padT + d.rows.length * rowH + padB,
          x0 = 250, x1 = W - 92, maxv = 80;
      var sx = function (v) { return x0 + (x1 - x0) * (v / maxv); };
      var s = "";

      [0, 20, 40, 60, 80].forEach(function (t) {
        s += '<line x1="' + sx(t) + '" y1="' + (padT - 8) + '" x2="' + sx(t) + '" y2="' +
             (H - padB) + '" stroke="' + LINE + '" stroke-width="1"/>' +
             '<text x="' + sx(t) + '" y="' + (H - padB + 20) + '" text-anchor="middle" ' +
             'font-family="IBM Plex Mono, monospace" font-size="12" fill="' + MUTED + '">' +
             t + (t === 80 ? "%" : "") + "</text>";
      });

      // the floor: the paper treats this as the number any representation has to beat
      s += '<line x1="' + sx(d.floor) + '" y1="' + (padT - 20) + '" x2="' + sx(d.floor) +
           '" y2="' + (H - padB) + '" stroke="' + INK + '" stroke-width="2" ' +
           'stroke-dasharray="5 4" opacity="0.55"/>' +
           '<text x="' + (sx(d.floor) + 8) + '" y="' + (padT - 8) + '" ' +
           'font-family="Source Sans 3, sans-serif" font-size="13" fill="' + SOFT + '">' +
           "no network at all &#183; " + d.floor + "%</text>";

      d.rows.forEach(function (r, i) {
        var y = padT + i * rowH, bh = 17, cy = y + bh / 2,
            col = r.highlight ? ACCENT : (r.acc < d.floor ? BLUE : MUTED);
        s += '<text x="' + (x0 - 14) + '" y="' + (cy - 2) + '" text-anchor="end" ' +
             'font-family="Source Sans 3, sans-serif" font-weight="600" font-size="15" fill="' +
             INK + '">' + esc(r.label) + "</text>" +
             '<text x="' + (x0 - 14) + '" y="' + (cy + 14) + '" text-anchor="end" ' +
             'font-family="Source Sans 3, sans-serif" font-size="12" fill="' + MUTED + '">' +
             esc(r.sub) + "</text>" +
             '<rect x="' + x0 + '" y="' + y + '" width="' + (x1 - x0) + '" height="' + bh +
             '" fill="#eeeae2"/>' +
             '<rect x="' + x0 + '" y="' + y + '" width="' + (sx(r.acc) - x0) + '" height="' + bh +
             '" fill="' + col + '"/>' +
             // 95% interval, drawn over the fill
             '<line x1="' + sx(r.lo) + '" y1="' + cy + '" x2="' + sx(r.hi) + '" y2="' + cy +
             '" stroke="' + INK + '" stroke-width="1.5" opacity="0.75"/>' +
             '<line x1="' + sx(r.lo) + '" y1="' + (cy - 5) + '" x2="' + sx(r.lo) + '" y2="' +
             (cy + 5) + '" stroke="' + INK + '" stroke-width="1.5" opacity="0.75"/>' +
             '<line x1="' + sx(r.hi) + '" y1="' + (cy - 5) + '" x2="' + sx(r.hi) + '" y2="' +
             (cy + 5) + '" stroke="' + INK + '" stroke-width="1.5" opacity="0.75"/>' +
             '<text x="' + (x1 + 12) + '" y="' + (cy + 5) + '" ' +
             'font-family="IBM Plex Mono, monospace" font-weight="500" font-size="15" fill="' +
             col + '">' + r.acc.toFixed(1) + "</text>";
      });

      host.innerHTML = svg(s, W, H);
      var cap = document.getElementById("accChartNote");
      if (cap) {
        /* results.json has always carried who is pooled and what "accuracy" counts. The page
         * never showed either, which is how a reader was left to guess the comparator. */
        cap.innerHTML = "Whiskers are 95% bootstrap intervals. Dashed line: the accuracy the " +
          "same models reach with no network in the prompt. Four renderings fall below it. " +
          "Readers pooled: " + esc(d.pool.split(";")[0]) + ". Every question counts, and a " +
          "prompt longer than the " + num(d.budget) + "-token budget is scored wrong because " +
          "the model never receives it.";
      }
    }).catch(function () {
      host.innerHTML = '<p class="widget-fail">Could not load the results file.</p>';
    });
  })();

  /* ---------------------------------------------------------- region explorer
   * Six real retrieved regions from the paper's Section S1. Removing the node the question asks
   * about is not a simulation: `after` records which component every node actually landed in,
   * computed by the graph algorithm, so the picture is the exact answer.
   *
   * Pieces are drawn in two colours rather than one per component. Eleven generated hues would
   * be unreadable, and the distinction that answers the question is binary: did this node stay
   * attached to the main body, or did it come away.
   */
  (function () {
    var host = document.getElementById("regionExplorer");
    if (!host) return;

    var DATA = null, cur = 0, removed = false, arm = "R5_BioGlyph";

    function mainComponent(reg) {
      var counts = {};
      Object.keys(reg.after).forEach(function (k) {
        counts[reg.after[k]] = (counts[reg.after[k]] || 0) + 1;
      });
      var best = null;
      Object.keys(counts).forEach(function (c) {
        if (best === null || counts[c] > counts[best]) best = c;
      });
      return best;
    }

    function drawRegion(reg) {
      var W = 720, H = 560, pad = 34, main = mainComponent(reg),
          goneSet = {}, focusSet = {};
      reg.gone.forEach(function (n) { goneSet[n] = 1; });
      reg.focus.forEach(function (n) { focusSet[n] = 1; });

      var xy = {};
      reg.nodes.forEach(function (n) {
        xy[n[0]] = [pad + n[1] * (W - 2 * pad), pad + n[2] * (H - 2 * pad)];
      });

      function detached(id) {
        return removed && !goneSet[id] && String(reg.after[id]) !== String(main);
      }

      var s = "";
      reg.edges.forEach(function (e) {
        var a = xy[e[0]], b = xy[e[1]];
        if (!a || !b) return;
        // an edge incident to the removed node disappears with it
        var cut = removed && (goneSet[e[0]] || goneSet[e[1]]);
        var col = cut ? "#efe9e7" : (detached(e[0]) && detached(e[1]) ? "#e0cdc9" : LINE);
        s += '<line x1="' + a[0].toFixed(1) + '" y1="' + a[1].toFixed(1) + '" x2="' +
             b[0].toFixed(1) + '" y2="' + b[1].toFixed(1) + '" stroke="' + col +
             '" stroke-width="' + (cut ? 0.8 : 1.1) + '"/>';
      });
      reg.nodes.forEach(function (n) {
        var id = n[0], p = xy[id], r = 5.5, col = BLUE, extra = "";
        if (goneSet[id]) {
          col = removed ? "#ffffff" : ACCENT;
          r = 9;
          extra = '<circle cx="' + p[0] + '" cy="' + p[1] + '" r="' + (r + 4) +
                  '" fill="none" stroke="' + ACCENT + '" stroke-width="2"' +
                  (removed ? ' stroke-dasharray="3 3"' : "") + "/>";
        } else if (detached(id)) {
          col = ACCENT;
          r = 6.5;
        } else if (focusSet[id]) {
          col = ACCENT;
        }
        s += '<circle cx="' + p[0].toFixed(1) + '" cy="' + p[1].toFixed(1) + '" r="' + r +
             '" fill="' + col + '"/>' + extra;
      });
      return svg(s, W, H);
    }

    function armRow(reg, a) {
      var pct = Math.min(100, (a.tokens / DATA.budget) * 100),
          over = a.tokens > DATA.budget,
          col = a.arm === "R5_BioGlyph" ? ACCENT : (over ? "#c08b84" : BLUE);
      return '<button class="arm-row' + (arm === a.arm ? " on" : "") + '" data-arm="' +
        esc(a.arm) + '" type="button">' +
        '<span class="arm-name">' + esc(a.label) + "</span>" +
        '<span class="arm-meter"><i style="width:' + pct.toFixed(1) + "%;background:" + col +
        '"></i></span>' +
        '<span class="arm-tok">' + num(a.tokens) + "</span>" +
        '<span class="arm-verdict ' + (a.sent ? (a.correct ? "yes" : "no") : "never") + '">' +
        (a.sent ? (a.correct ? "correct" : "wrong") : "never sent") + "</span></button>";
    }

    function render() {
      var reg = DATA.regions[cur],
          a = reg.arms.filter(function (x) { return x.arm === arm; })[0],
          body = arm === "R5_BioGlyph" ? reg.context_r5
               : arm === "R3_RawMetrics" ? reg.context_r3_head
               : null;

      host.innerHTML =
        '<div class="rx-picker">' + DATA.regions.map(function (r, i) {
          return '<button type="button" class="rx-tab' + (i === cur ? " on" : "") +
            '" data-i="' + i + '">' + esc(r.dataset) + '<small>' +
            esc(r.family.replace(/_/g, " ")) + "</small></button>";
        }).join("") + "</div>" +

        '<div class="rx-grid">' +
          '<div class="rx-figure">' +
            '<div class="rx-canvas">' + drawRegion(reg) + "</div>" +
            '<div class="rx-controls">' +
              '<button type="button" id="rxRemove" class="button ' +
                (removed ? "primary" : "ghost") + '">' +
                (removed ? "Put it back" : "Remove node " + esc(reg.gone[0])) + "</button>" +
              '<span class="rx-legend">' +
                '<span><i class="sw-blue"></i>still attached</span>' +
                '<span><i class="sw-accent"></i>' +
                  (removed ? "came away" : "the node in question") + "</span></span>" +
            "</div>" +
            '<p class="rx-state">' + (removed
              ? "Removing it leaves <b>" + reg.pieces + " piece" + (reg.pieces === 1 ? "" : "s") +
                "</b>. That count is computed by the graph algorithm, not estimated."
              : "A real retrieved region: <b>" + num(reg.n_nodes) + " nodes, " +
                num(reg.n_edges) + " edges</b>." ) + "</p>" +
          "</div>" +

          '<div class="rx-side">' +
            '<div class="rx-q"><span class="eyebrow">The question</span><p>' +
              esc(reg.question) + "</p></div>" +
            '<div class="rx-answers">' +
              '<div><small>Exact algorithm</small><b>' + esc(reg.gold) + "</b></div>" +
              '<div class="' + (reg.model_correct ? "ok" : "bad") + '"><small>' +
                "Model, reading BioGlyph</small><b>" + esc(reg.model_answer || "—") +
              "</b></div>" +
            "</div>" +
            '<div class="rx-arms"><span class="eyebrow">Prompt length against the ' +
              num(DATA.budget) + "-token limit</span>" +
              reg.arms.map(function (x) { return armRow(reg, x); }).join("") + "</div>" +
          "</div>" +
        "</div>" +

        '<div class="rx-context">' +
          (body === null
            ? '<p class="rx-nocontext">This rendering is not shipped with the page. Pick the ' +
              "compiled description or the raw measurement table to read the actual text.</p>"
            : '<div class="rx-context-head"><b>' + esc(a.label) + "</b>" +
              (arm === "R3_RawMetrics"
                ? "<span>first 70 of " + num(reg.context_r3_lines) + " lines &#183; " +
                  num(a.tokens) + " tokens in full" +
                  (a.sent ? "" : ", over the limit, so it never reached the model") + "</span>"
                : "<span>" + num(a.tokens) + " tokens, complete</span>") +
              "</div><pre>" + esc(body) + "</pre>") +
        "</div>";

      var rm = document.getElementById("rxRemove");
      if (rm) rm.addEventListener("click", function () { removed = !removed; render(); });
      host.querySelectorAll(".rx-tab").forEach(function (b) {
        b.addEventListener("click", function () {
          cur = Number(b.getAttribute("data-i"));
          removed = false;
          render();
        });
      });
      host.querySelectorAll(".arm-row").forEach(function (b) {
        b.addEventListener("click", function () {
          arm = b.getAttribute("data-arm");
          render();
        });
      });
    }

    fetch("assets/regions.json").then(function (r) { return r.json(); }).then(function (d) {
      DATA = d;
      render();
    }).catch(function () {
      host.innerHTML = '<p class="widget-fail">Could not load the region data.</p>';
    });
  })();

  /* ------------------------------------------------------ conversation player
   * Ten real eight-turn conversations, five regions, two models. Nothing here is generated at
   * view time: every question, every reply and every verdict is the stored one from the runs the
   * paper scores, and the verdicts are the evaluator's, not a reading of the reply.
   *
   * The claim the widget exists to show is that the description is sent ONCE, at turn 1, and
   * still carries turn 8. So the prompt length is on screen at every turn: it starts at the
   * description's length and grows only by the conversation itself.
   */
  (function () {
    var host = document.getElementById("threadPlayer");
    if (!host) return;

    var DATA = null, ti = 0, mi = 0, turn = 0, removed = false;

    var CLS = {
      graded:   ["graded", "checked against the exact algorithm"],
      lookup:   ["lookup", "the answer is stated in the description"],
      unscored: ["opinion", "an explanation, not scored"],
      pushback: ["push-back", "we told it its earlier answer was wrong"]
    };
    /* Two threads can share a region and a removal type, so the dataset alone does not name a
     * thread. The kind is what actually distinguishes them. */
    var KIND = {
      knockout: "which node breaks it",
      reach:    "can they still reach each other",
      edge:     "which link holds it together",
      roles:    "what roles does it hold",
      compose:  "two facts combined"
    };

    function thread() { return DATA.threads[ti]; }
    function model() { return thread().models[mi]; }

    function mainComponent(t) {
      var counts = {}, best = null;
      Object.keys(t.after).forEach(function (k) {
        counts[t.after[k]] = (counts[t.after[k]] || 0) + 1;
      });
      Object.keys(counts).forEach(function (c) {
        if (best === null || counts[c] > counts[best]) best = c;
      });
      return best;
    }

    /* Same two-colour rule as the region explorer: eleven generated hues would be unreadable, and
     * the distinction that answers the question is binary -- did this stay attached, or not. */
    function draw(t) {
      var W = 720, H = 520, pad = 30, main = mainComponent(t),
          goneSet = {}, focusSet = {}, xy = {};
      t.gone.forEach(function (n) { goneSet[n] = 1; });
      t.focus.forEach(function (n) { focusSet[n] = 1; });
      t.nodes.forEach(function (n) {
        xy[n[0]] = [pad + n[1] * (W - 2 * pad), pad + n[2] * (H - 2 * pad)];
      });

      // an edge thread cuts the link between its two focus nodes; a knockout thread deletes a node
      var cutA = t.removes === "edge" && t.focus.length === 2 ? t.focus[0] : null,
          cutB = t.removes === "edge" && t.focus.length === 2 ? t.focus[1] : null;

      function detached(id) {
        return removed && !goneSet[id] && String(t.after[id]) !== String(main);
      }

      var s = "";
      t.edges.forEach(function (e) {
        var a = xy[e[0]], b = xy[e[1]];
        if (!a || !b) return;
        var isCut = removed && ((goneSet[e[0]] || goneSet[e[1]]) ||
              (cutA !== null && ((e[0] === cutA && e[1] === cutB) || (e[0] === cutB && e[1] === cutA))));
        var col = isCut ? "#efe9e7" : (detached(e[0]) && detached(e[1]) ? "#e0cdc9" : LINE);
        s += '<line x1="' + a[0].toFixed(1) + '" y1="' + a[1].toFixed(1) + '" x2="' +
             b[0].toFixed(1) + '" y2="' + b[1].toFixed(1) + '" stroke="' + col +
             '" stroke-width="' + (isCut ? 0.8 : 1.1) + '"/>';
      });
      t.nodes.forEach(function (n) {
        var id = n[0], p = xy[id], r = 5.5, col = BLUE, extra = "";
        if (goneSet[id]) {
          col = removed ? "#ffffff" : ACCENT;
          r = 9;
          extra = '<circle cx="' + p[0] + '" cy="' + p[1] + '" r="' + (r + 4) +
                  '" fill="none" stroke="' + ACCENT + '" stroke-width="2"' +
                  (removed ? ' stroke-dasharray="3 3"' : "") + "/>";
        } else if (detached(id)) {
          col = ACCENT; r = 6.5;
        } else if (focusSet[id]) {
          col = ACCENT; r = 7.5;
        }
        s += '<circle cx="' + p[0].toFixed(1) + '" cy="' + p[1].toFixed(1) + '" r="' + r +
             '" fill="' + col + '"/>' + extra;
      });
      return svg(s, W, H);
    }

    function nameOf(t, id) {
      var g = t.genes[String(id)];
      return g ? esc(g) + " (node " + id + ")" : "node " + id;
    }

    function eventText(t) {
      return t.removes === "edge" && t.focus.length === 2
        ? "Cut the link between " + nameOf(t, t.focus[0]) + " and " + nameOf(t, t.focus[1])
        : "Remove " + nameOf(t, t.gone[0] !== undefined ? t.gone[0] : t.focus[0]);
    }

    function verdict(tn) {
      if (tn.correct === true) return '<span class="tp-v yes">agrees with the algorithm</span>';
      if (tn.correct === false) return '<span class="tp-v no">disagrees</span>';
      return '<span class="tp-v na">not scored</span>';
    }

    function render() {
      var t = thread(), m = model(), tn = m.turns[turn],
          cls = CLS[tn.cls] || [tn.cls, ""],
          grew = tn.tokens - t.context_tokens;

      host.innerHTML =
        '<div class="tp-picker">' + DATA.threads.map(function (x, i) {
          return '<button type="button" class="rx-tab' + (i === ti ? " on" : "") +
            '" data-i="' + i + '">' + esc(x.dataset) + "<small>" +
            esc(KIND[x.kind] || x.kind) + "</small></button>";
        }).join("") + "</div>" +

        '<div class="tp-grid">' +
          '<div class="rx-figure">' +
            '<div class="rx-canvas">' + draw(t) + "</div>" +
            '<div class="rx-controls">' +
              '<button type="button" id="tpRemove" class="button ' +
                (removed ? "primary" : "ghost") + '">' +
                (removed ? "Put it back" : esc(eventText(t))) + "</button>" +
              '<span class="rx-legend">' +
                '<span><i class="sw-blue"></i>still attached</span>' +
                '<span><i class="sw-accent"></i>' +
                (removed ? "came away" : "what the conversation is about") + "</span></span>" +
            "</div>" +
            '<p class="rx-state">' + (removed
              ? "The region is left in <b>" + t.pieces + " piece" + (t.pieces === 1 ? "" : "s") +
                "</b>, counted by the graph algorithm."
              : "One retrieved region: <b>" + num(t.n_nodes) + " nodes, " + num(t.n_edges) +
                " links</b>. The model saw it described once, then answered eight questions.") +
            "</p>" +
          "</div>" +

          '<div class="tp-side">' +
            '<div class="tp-models">' + t.models.map(function (x, i) {
              return '<button type="button" class="tp-model' + (i === mi ? " on" : "") +
                '" data-m="' + i + '">' + esc(x.model) + "<small>" + x.correct + " of " +
                x.scored + " graded turns right</small></button>";
            }).join("") + "</div>" +

            '<div class="tp-budget">' +
              "<b>One description, sent at turn 1 only.</b> " + num(t.context_tokens) +
              " tokens. " + (grew <= 0
                ? "That is the whole of this first prompt. It is never sent again."
                : "By turn " + tn.turn + " the prompt is " + num(tn.tokens) + " &mdash; the " +
                  num(grew) + " added since are the questions and replies themselves, not the " +
                  "region being resent.") +
            "</div>" +

            '<div class="tp-rail">' + m.turns.map(function (x, i) {
              var st = x.correct === true ? "yes" : x.correct === false ? "no" : "na";
              return '<button type="button" class="tp-step ' + st + (i === turn ? " on" : "") +
                '" data-t="' + i + '" title="Turn ' + x.turn + ' &middot; ' + esc(x.label) +
                '">' + x.turn + "</button>";
            }).join("") + "</div>" +

            '<article class="tp-turn">' +
              '<div class="tp-turn-head"><span class="tp-cls ' + esc(tn.cls) + '">' +
                esc(cls[0]) + "</span><small>" + esc(cls[1]) + "</small></div>" +
              '<p class="tp-q">' + esc(tn.q) + "</p>" +
              '<div class="tp-a"><small>' + esc(m.model) + " replied</small><p>" +
                esc(tn.a || "—") + "</p></div>" +
              (tn.cls === "unscored" ? ""
                : '<div class="tp-gold"><small>Exact algorithm</small><b>' +
                  esc(tn.gold || "—") + "</b>" + verdict(tn) + "</div>") +
            "</article>" +

            '<div class="tp-nav">' +
              '<button type="button" class="button ghost" id="tpPrev"' +
                (turn === 0 ? " disabled" : "") + ">Previous turn</button>" +
              '<button type="button" class="button ghost" id="tpNext"' +
                (turn === m.turns.length - 1 ? " disabled" : "") + ">Next turn</button>" +
              "<span>turn " + (turn + 1) + " of " + m.turns.length + "</span>" +
            "</div>" +
          "</div>" +
        "</div>" +

        '<details class="tp-context"><summary>Read the description the model was given, once, ' +
          "at turn 1 &mdash; " + num(t.context_tokens) + " tokens</summary><pre>" +
          esc(t.context) + "</pre></details>";

      var rm = document.getElementById("tpRemove");
      if (rm) rm.addEventListener("click", function () { removed = !removed; render(); });
      var pv = document.getElementById("tpPrev");
      if (pv) pv.addEventListener("click", function () { if (turn > 0) { turn--; render(); } });
      var nx = document.getElementById("tpNext");
      if (nx) nx.addEventListener("click", function () {
        if (turn < model().turns.length - 1) { turn++; render(); }
      });
      host.querySelectorAll(".rx-tab").forEach(function (b) {
        b.addEventListener("click", function () {
          ti = Number(b.getAttribute("data-i"));
          mi = 0; turn = 0; removed = false;
          render();
        });
      });
      host.querySelectorAll(".tp-model").forEach(function (b) {
        b.addEventListener("click", function () {
          mi = Number(b.getAttribute("data-m")); render();
        });
      });
      host.querySelectorAll(".tp-step").forEach(function (b) {
        b.addEventListener("click", function () {
          turn = Number(b.getAttribute("data-t")); render();
        });
      });
    }

    fetch("assets/threads.json").then(function (r) { return r.json(); }).then(function (d) {
      DATA = d;
      render();
    }).catch(function () {
      host.innerHTML = '<p class="widget-fail">Could not load the conversation data.</p>';
    });
  })();

  /* ------------------------------------------------------- the paired study
   * The same three-turn conversation, once through the compiled description and once through the
   * raw measurement table. On the yeast region the table is 39,784 tokens at turn 1, so it never
   * reaches the model and the conversation never starts. That is what the pooled 39.5% is made of.
   */
  (function () {
    var host = document.getElementById("pairedTurns");
    if (!host) return;

    var DATA = null, pi = 0;

    function column(p, a) {
      var over = a.turns.some(function (t) { return !t.sent; });
      return '<div class="pt-col' + (over ? " dead" : "") + '">' +
        '<div class="pt-col-head"><b>' + esc(a.label) + "</b><small>" +
          (over ? "never reached the model" : "every turn delivered") + "</small></div>" +
        a.turns.map(function (t) {
          var pct = Math.min(100, (t.tokens / DATA.budget) * 100);
          return '<div class="pt-turn">' +
            '<div class="pt-turn-top"><span>Turn ' + t.turn + "</span>" +
              '<span class="tp-v ' + (!t.sent ? "never" : t.correct ? "yes" : "no") + '">' +
              (!t.sent ? "over the limit" : t.correct ? "correct" : "wrong") + "</span></div>" +
            '<div class="arm-meter"><i style="width:' + pct.toFixed(1) + "%;background:" +
              (t.sent ? ACCENT : "#c08b84") + '"></i></div>' +
            '<div class="pt-tok">' + num(t.tokens) + " tokens</div>" +
          "</div>";
        }).join("") + "</div>";
    }

    function render() {
      var p = DATA.paired[pi];
      host.innerHTML =
        '<div class="tp-picker">' + DATA.paired.map(function (x, i) {
          return '<button type="button" class="rx-tab' + (i === pi ? " on" : "") +
            '" data-i="' + i + '">' + esc(x.dataset) + "<small>" + esc(x.model) +
            "</small></button>";
        }).join("") + "</div>" +
        '<div class="pt-grid">' + p.arms.map(function (a) { return column(p, a); }).join("") +
        "</div>" +
        '<p class="pt-note">Both columns are the same three questions about the same ' +
          num(p.n_nodes) + "-node region, answered by " + esc(p.model) +
          ". The bar is prompt length against the " + num(DATA.budget) +
          "-token budget. A prompt over that budget is never sent, so it is scored wrong and " +
          "there is no reply to follow up on.</p>";

      host.querySelectorAll(".rx-tab").forEach(function (b) {
        b.addEventListener("click", function () {
          pi = Number(b.getAttribute("data-i")); render();
        });
      });
    }

    fetch("assets/threads.json").then(function (r) { return r.json(); }).then(function (d) {
      DATA = d;
      render();
    }).catch(function () {
      host.innerHTML = '<p class="widget-fail">Could not load the conversation data.</p>';
    });
  })();

  /* ------------------------------------------------------------- live query
   * The workspace sits behind the lab's sign-in gate, so a reader of the paper with no account
   * used to hit a login wall. This asks the open read-only route instead, the same shape scVision
   * uses for /annotate.
   *
   * The block stays hidden until that route answers. If it is not deployed, or the GPU is down,
   * the page simply keeps the link to the workspace rather than offering a button that fails --
   * scvision/interactive.js hides its own live button the same way.
   */
  (function () {
    var host = document.getElementById("liveAsk");
    if (!host || !window.BIOGLYPH_API) return;

    var API = String(window.BIOGLYPH_API).replace(/\/+$/, ""),
        CFG = null, arm = "R5_BioGlyph", busy = false;

    function shell(body) {
      return '<div class="live-head"><span class="live-dot"></span>Live &middot; ' +
        esc(CFG.model) + "</div>" + body;
    }

    function controls() {
      return '<label class="live-label" for="liveGraph">Network</label>' +
        '<select id="liveGraph">' + CFG.graphs.map(function (g) {
          return '<option value="' + esc(g.name) + '">' + esc(g.name) + " &mdash; " +
            num(g.nodes) + " nodes</option>";
        }).join("") + "</select>" +
        '<div class="live-arms">' + [["R5_BioGlyph", "Compiled description"],
                                     ["R3_RawMetrics", "Raw measurements"]].map(function (a) {
          return '<button type="button" class="live-arm' + (arm === a[0] ? " on" : "") +
            '" data-arm="' + a[0] + '">' + a[1] + "</button>";
        }).join("") + "</div>" +
        '<div class="live-row"><input id="liveQ" type="text" autocomplete="off" ' +
          'placeholder="Is node 17 an articulation point?"><button type="button" ' +
          'class="button primary" id="liveGo">Ask</button></div>' +
        '<div class="live-ex" id="liveEx"></div>' +
        '<div id="liveOut"></div>';
    }

    function examples() {
      var g = CFG.graphs.filter(function (x) {
        return x.name === document.getElementById("liveGraph").value;
      })[0];
      document.getElementById("liveEx").innerHTML = (g.examples || []).slice(0, 3)
        .map(function (e) { return '<button type="button" data-q="' + esc(e) + '">' +
                                   esc(e) + "</button>"; }).join("");
      wireEx();
    }

    function wireEx() {
      host.querySelectorAll(".live-ex button").forEach(function (b) {
        b.addEventListener("click", function () {
          document.getElementById("liveQ").value = b.getAttribute("data-q");
          run();
        });
      });
    }

    function say(cls, html) {
      document.getElementById("liveOut").innerHTML =
        '<div class="live-out ' + cls + '">' + html + "</div>";
    }

    function run() {
      if (busy) return;
      var q = document.getElementById("liveQ").value.trim();
      if (!q) return;
      busy = true;
      document.getElementById("liveGo").disabled = true;
      say("busy", "Compiling the region and asking the model&hellip;");
      fetch(API + "/ask", {
        method: "POST", headers: {"content-type": "application/json"},
        body: JSON.stringify({question: q, graph: document.getElementById("liveGraph").value,
                              arm: arm})
      }).then(function (r) {
        return r.json().then(function (d) { return {ok: r.ok, d: d}; });
      }).then(function (res) {
        if (!res.ok) { say("bad", esc(res.d.detail || "That question could not be answered.")); return; }
        var d = res.d;
        if (d.overflowed) {
          say("bad", "<b>Nothing reached the model.</b> Rendering this " + num(d.region_nodes) +
            "-node region as raw measurements takes " + num(d.prompt_tokens) +
            " tokens and the window holds " + num(d.window) + ", so there was no prompt to send. " +
            "Ask the same question on the compiled description. The exact answer is still <code>" +
            esc(d.oracle) + "</code>.");
          return;
        }
        say("good",
          '<div class="live-pair"><div><small>The model, reading ' +
            (arm === "R5_BioGlyph" ? "the description" : "the table") + "</small><p>" +
            esc(d.answer) + "</p></div>" +
          "<div><small>Exact algorithm</small><b>" + esc(d.oracle) + "</b></div></div>" +
          '<p class="live-meta">' + esc(d.family) + " &middot; region " + num(d.region_nodes) +
          " nodes &middot; " + num(d.prompt_tokens) + " of " + num(d.window) + " tokens &middot; " +
          d.seconds + "s</p>");
      }).catch(function () {
        say("bad", "Could not reach the model. It may be waking up &mdash; try again in a moment.");
      }).then(function () {
        busy = false;
        document.getElementById("liveGo").disabled = false;
      });
    }

    function render() {
      host.innerHTML = shell(controls());
      host.hidden = false;
      examples();
      document.getElementById("liveGraph").addEventListener("change", examples);
      document.getElementById("liveGo").addEventListener("click", run);
      document.getElementById("liveQ").addEventListener("keydown", function (e) {
        if (e.key === "Enter") run();
      });
      host.querySelectorAll(".live-arm").forEach(function (b) {
        b.addEventListener("click", function () {
          arm = b.getAttribute("data-arm");
          host.querySelectorAll(".live-arm").forEach(function (x) { x.classList.remove("on"); });
          b.classList.add("on");
        });
      });
    }

    fetch(API + "/graphs").then(function (r) {
      if (!r.ok) throw new Error("no route");
      return r.json();
    }).then(function (d) {
      if (!d.graphs || !d.graphs.length) throw new Error("no graphs");
      CFG = d;
      render();
    }).catch(function () {
      /* leave the block hidden: the workspace link beside it still works */
    });
  })();
})();
