/* BioGlyph project page widgets.
 *
 * Structure copied from scvision/interactive.js: one file, no dependencies, no build step, and
 * one self-guarding IIFE per widget so a missing element or a failed fetch takes out that widget
 * alone. Charts are hand-written inline SVG strings.
 *
 * Every number rendered here comes from assets/regions.json or assets/results.json, both
 * generated by build_data.py out of the manuscript's own figure data. Nothing is typed into the
 * markup, so the page cannot drift from the paper.
 */
(function () {
  "use strict";

  var INK = "#17202c", SOFT = "#465262", MUTED = "#707a86", LINE = "#d9d6ce",
      ACCENT = "#a83f35", BLUE = "#476d89", WARM = "#f5f3ee";

  function esc(s) {
    return String(s == null ? "" : s).replace(/[&<>"]/g, function (c) {
      return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;" }[c];
    });
  }
  function num(n) { return Number(n).toLocaleString(); }
  function svg(inner, vw, vh) {
    return '<svg viewBox="0 0 ' + vw + " " + vh + '" preserveAspectRatio="xMidYMid meet" ' +
           'role="img" xmlns="http://www.w3.org/2000/svg">' + inner + "</svg>";
  }

  /* ------------------------------------------------------------------ chart
   * Accuracy by representation. One series, sorted, direct labels, plus the two things the
   * markup version could not show: the confidence interval as a whisker, and the blind floor as
   * a reference line. Whether 70.6 and 64.3 overlap is exactly what a reader wants to see.
   */
  (function () {
    var host = document.getElementById("accChart");
    if (!host) return;

    fetch("assets/results.json").then(function (r) { return r.json(); }).then(function (d) {
      var W = 1000, rowH = 46, padT = 34, padB = 30,
          H = padT + d.rows.length * rowH + padB,
          x0 = 250, x1 = W - 92, maxv = 80;
      var sx = function (v) { return x0 + (x1 - x0) * (v / maxv); };
      var s = "";

      [0, 20, 40, 60, 80].forEach(function (t) {
        s += '<line x1="' + sx(t) + '" y1="' + (padT - 8) + '" x2="' + sx(t) + '" y2="' +
             (H - padB) + '" stroke="' + LINE + '" stroke-width="1"/>' +
             '<text x="' + sx(t) + '" y="' + (H - padB + 20) + '" text-anchor="middle" ' +
             'font-family="IBM Plex Mono, monospace" font-size="12" fill="' + MUTED + '">' +
             t + (t === 80 ? "%" : "") + "</text>";
      });

      // the floor: the paper treats this as the number any representation has to beat
      s += '<line x1="' + sx(d.floor) + '" y1="' + (padT - 20) + '" x2="' + sx(d.floor) +
           '" y2="' + (H - padB) + '" stroke="' + INK + '" stroke-width="2" ' +
           'stroke-dasharray="5 4" opacity="0.55"/>' +
           '<text x="' + (sx(d.floor) + 8) + '" y="' + (padT - 8) + '" ' +
           'font-family="Source Sans 3, sans-serif" font-size="13" fill="' + SOFT + '">' +
           "no network at all &#183; " + d.floor + "%</text>";

      d.rows.forEach(function (r, i) {
        var y = padT + i * rowH, bh = 17, cy = y + bh / 2,
            col = r.highlight ? ACCENT : (r.acc < d.floor ? BLUE : MUTED);
        s += '<text x="' + (x0 - 14) + '" y="' + (cy - 2) + '" text-anchor="end" ' +
             'font-family="Source Sans 3, sans-serif" font-weight="600" font-size="15" fill="' +
             INK + '">' + esc(r.label) + "</text>" +
             '<text x="' + (x0 - 14) + '" y="' + (cy + 14) + '" text-anchor="end" ' +
             'font-family="Source Sans 3, sans-serif" font-size="12" fill="' + MUTED + '">' +
             esc(r.sub) + "</text>" +
             '<rect x="' + x0 + '" y="' + y + '" width="' + (x1 - x0) + '" height="' + bh +
             '" fill="#eeeae2"/>' +
             '<rect x="' + x0 + '" y="' + y + '" width="' + (sx(r.acc) - x0) + '" height="' + bh +
             '" fill="' + col + '"/>' +
             // 95% interval, drawn over the fill
             '<line x1="' + sx(r.lo) + '" y1="' + cy + '" x2="' + sx(r.hi) + '" y2="' + cy +
             '" stroke="' + INK + '" stroke-width="1.5" opacity="0.75"/>' +
             '<line x1="' + sx(r.lo) + '" y1="' + (cy - 5) + '" x2="' + sx(r.lo) + '" y2="' +
             (cy + 5) + '" stroke="' + INK + '" stroke-width="1.5" opacity="0.75"/>' +
             '<line x1="' + sx(r.hi) + '" y1="' + (cy - 5) + '" x2="' + sx(r.hi) + '" y2="' +
             (cy + 5) + '" stroke="' + INK + '" stroke-width="1.5" opacity="0.75"/>' +
             '<text x="' + (x1 + 12) + '" y="' + (cy + 5) + '" ' +
             'font-family="IBM Plex Mono, monospace" font-weight="500" font-size="15" fill="' +
             col + '">' + r.acc.toFixed(1) + "</text>";
      });

      host.innerHTML = svg(s, W, H);
      var cap = document.getElementById("accChartNote");
      if (cap) {
        cap.innerHTML = "Whiskers are 95% bootstrap intervals. Dashed line: the accuracy the " +
          "same models reach with no network in the prompt. Two renderings fall below it.";
      }
    }).catch(function () {
      host.innerHTML = '<p class="widget-fail">Could not load the results file.</p>';
    });
  })();

  /* ---------------------------------------------------------- region explorer
   * Six real retrieved regions from the paper's Section S1. Removing the node the question asks
   * about is not a simulation: `after` records which component every node actually landed in,
   * computed by the graph algorithm, so the picture is the exact answer.
   *
   * Pieces are drawn in two colours rather than one per component. Eleven generated hues would
   * be unreadable, and the distinction that answers the question is binary: did this node stay
   * attached to the main body, or did it come away.
   */
  (function () {
    var host = document.getElementById("regionExplorer");
    if (!host) return;

    var DATA = null, cur = 0, removed = false, arm = "R5_BioGlyph";

    function mainComponent(reg) {
      var counts = {};
      Object.keys(reg.after).forEach(function (k) {
        counts[reg.after[k]] = (counts[reg.after[k]] || 0) + 1;
      });
      var best = null;
      Object.keys(counts).forEach(function (c) {
        if (best === null || counts[c] > counts[best]) best = c;
      });
      return best;
    }

    function drawRegion(reg) {
      var W = 720, H = 560, pad = 34, main = mainComponent(reg),
          goneSet = {}, focusSet = {};
      reg.gone.forEach(function (n) { goneSet[n] = 1; });
      reg.focus.forEach(function (n) { focusSet[n] = 1; });

      var xy = {};
      reg.nodes.forEach(function (n) {
        xy[n[0]] = [pad + n[1] * (W - 2 * pad), pad + n[2] * (H - 2 * pad)];
      });

      function detached(id) {
        return removed && !goneSet[id] && String(reg.after[id]) !== String(main);
      }

      var s = "";
      reg.edges.forEach(function (e) {
        var a = xy[e[0]], b = xy[e[1]];
        if (!a || !b) return;
        // an edge incident to the removed node disappears with it
        var cut = removed && (goneSet[e[0]] || goneSet[e[1]]);
        var col = cut ? "#efe9e7" : (detached(e[0]) && detached(e[1]) ? "#e0cdc9" : LINE);
        s += '<line x1="' + a[0].toFixed(1) + '" y1="' + a[1].toFixed(1) + '" x2="' +
             b[0].toFixed(1) + '" y2="' + b[1].toFixed(1) + '" stroke="' + col +
             '" stroke-width="' + (cut ? 0.8 : 1.1) + '"/>';
      });
      reg.nodes.forEach(function (n) {
        var id = n[0], p = xy[id], r = 5.5, col = BLUE, extra = "";
        if (goneSet[id]) {
          col = removed ? "#ffffff" : ACCENT;
          r = 9;
          extra = '<circle cx="' + p[0] + '" cy="' + p[1] + '" r="' + (r + 4) +
                  '" fill="none" stroke="' + ACCENT + '" stroke-width="2"' +
                  (removed ? ' stroke-dasharray="3 3"' : "") + "/>";
        } else if (detached(id)) {
          col = ACCENT;
          r = 6.5;
        } else if (focusSet[id]) {
          col = ACCENT;
        }
        s += '<circle cx="' + p[0].toFixed(1) + '" cy="' + p[1].toFixed(1) + '" r="' + r +
             '" fill="' + col + '"/>' + extra;
      });
      return svg(s, W, H);
    }

    function armRow(reg, a) {
      var pct = Math.min(100, (a.tokens / DATA.budget) * 100),
          over = a.tokens > DATA.budget,
          col = a.arm === "R5_BioGlyph" ? ACCENT : (over ? "#c08b84" : BLUE);
      return '<button class="arm-row' + (arm === a.arm ? " on" : "") + '" data-arm="' +
        esc(a.arm) + '" type="button">' +
        '<span class="arm-name">' + esc(a.label) + "</span>" +
        '<span class="arm-meter"><i style="width:' + pct.toFixed(1) + "%;background:" + col +
        '"></i></span>' +
        '<span class="arm-tok">' + num(a.tokens) + "</span>" +
        '<span class="arm-verdict ' + (a.sent ? (a.correct ? "yes" : "no") : "never") + '">' +
        (a.sent ? (a.correct ? "correct" : "wrong") : "never sent") + "</span></button>";
    }

    function render() {
      var reg = DATA.regions[cur],
          a = reg.arms.filter(function (x) { return x.arm === arm; })[0],
          body = arm === "R5_BioGlyph" ? reg.context_r5
               : arm === "R3_RawMetrics" ? reg.context_r3_head
               : null;

      host.innerHTML =
        '<div class="rx-picker">' + DATA.regions.map(function (r, i) {
          return '<button type="button" class="rx-tab' + (i === cur ? " on" : "") +
            '" data-i="' + i + '">' + esc(r.dataset) + '<small>' +
            esc(r.family.replace(/_/g, " ")) + "</small></button>";
        }).join("") + "</div>" +

        '<div class="rx-grid">' +
          '<div class="rx-figure">' +
            '<div class="rx-canvas">' + drawRegion(reg) + "</div>" +
            '<div class="rx-controls">' +
              '<button type="button" id="rxRemove" class="button ' +
                (removed ? "primary" : "ghost") + '">' +
                (removed ? "Put it back" : "Remove node " + esc(reg.gone[0])) + "</button>" +
              '<span class="rx-legend">' +
                '<span><i class="sw-blue"></i>still attached</span>' +
                '<span><i class="sw-accent"></i>' +
                  (removed ? "came away" : "the node in question") + "</span></span>" +
            "</div>" +
            '<p class="rx-state">' + (removed
              ? "Removing it leaves <b>" + reg.pieces + " piece" + (reg.pieces === 1 ? "" : "s") +
                "</b>. That count is computed by the graph algorithm, not estimated."
              : "A real retrieved region: <b>" + num(reg.n_nodes) + " nodes, " +
                num(reg.n_edges) + " edges</b>." ) + "</p>" +
          "</div>" +

          '<div class="rx-side">' +
            '<div class="rx-q"><span class="eyebrow">The question</span><p>' +
              esc(reg.question) + "</p></div>" +
            '<div class="rx-answers">' +
              '<div><small>Exact algorithm</small><b>' + esc(reg.gold) + "</b></div>" +
              '<div class="' + (reg.model_correct ? "ok" : "bad") + '"><small>' +
                "Model, reading BioGlyph</small><b>" + esc(reg.model_answer || "—") +
              "</b></div>" +
            "</div>" +
            '<div class="rx-arms"><span class="eyebrow">Prompt length against the ' +
              num(DATA.budget) + "-token limit</span>" +
              reg.arms.map(function (x) { return armRow(reg, x); }).join("") + "</div>" +
          "</div>" +
        "</div>" +

        '<div class="rx-context">' +
          (body === null
            ? '<p class="rx-nocontext">This rendering is not shipped with the page. Pick the ' +
              "compiled description or the raw measurement table to read the actual text.</p>"
            : '<div class="rx-context-head"><b>' + esc(a.label) + "</b>" +
              (arm === "R3_RawMetrics"
                ? "<span>first 70 of " + num(reg.context_r3_lines) + " lines &#183; " +
                  num(a.tokens) + " tokens in full" +
                  (a.sent ? "" : ", over the limit, so it never reached the model") + "</span>"
                : "<span>" + num(a.tokens) + " tokens, complete</span>") +
              "</div><pre>" + esc(body) + "</pre>") +
        "</div>";

      var rm = document.getElementById("rxRemove");
      if (rm) rm.addEventListener("click", function () { removed = !removed; render(); });
      host.querySelectorAll(".rx-tab").forEach(function (b) {
        b.addEventListener("click", function () {
          cur = Number(b.getAttribute("data-i"));
          removed = false;
          render();
        });
      });
      host.querySelectorAll(".arm-row").forEach(function (b) {
        b.addEventListener("click", function () {
          arm = b.getAttribute("data-arm");
          render();
        });
      });
    }

    fetch("assets/regions.json").then(function (r) { return r.json(); }).then(function (d) {
      DATA = d;
      render();
    }).catch(function () {
      host.innerHTML = '<p class="widget-fail">Could not load the region data.</p>';
    });
  })();
})();
